sudo: false
language: go
go:
- stable

before_install:
- go get -u golang.org/x/lint/golint
- go get -u github.com/mattn/goveralls

script:
- make all
- $GOPATH/bin/goveralls -service=travis-ci

after_success:
- bash <(curl -s https://codecov.io/bash)
