---
sudo: false
matrix:
  include:
    # markdownlint: https://github.com/markdownlint/markdownlint
    # https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
    - name: markdownlint
      language: ruby
      install:
        - gem install mdl
      script:
        - >
          find . -regextype egrep -iregex '.*\.md' -print0 |
            xargs -0rt mdl

    # shellcheck
    - name: shellcheck
      language: bash
      script:
        - >
          find . -regextype egrep -iregex '.*\.(ba)?sh' -print0 |
            xargs -0rt shellcheck

    # yamllint
    - name: yamllint
      language: python
      install:
        - pip install yamllint
      script:
        - >
          find . -regextype egrep -iregex '.*\.ya?ml' -print0 |
            xargs -0rt yamllint

    # Run golang tests
    - name: Unit tests
      language: go
      go:
        - stable
      install:
        - go get -u golang.org/x/lint/golint
        - go get -u github.com/mattn/goveralls
      script:
        - make all
        - $GOPATH/bin/goveralls -service=travis-ci
